"""create table birds

Revision ID: 181b4f7da4ae
Revises: 
Create Date: 2024-11-06 12:08:02.582440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181b4f7da4ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
